spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=tasklist
    username: postgres
    password: Rts28022007
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist


security:
  jwt:
    secret: Z2ZoZ2pramZjamdiZmdmZGdqaGtnamhjZmZzZHpzZnZjYm5oZmdnZmdm
    access: 3600000
    refresh: 2592000000
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml