spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=tasklist
    username: postgres
    password: Rts28022007
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: Z2ZoZ2pramZjamdiZmdmZGdqaGtnamhjZmZzZHpzZnZjYm5oZmdnZmdm
    access: 3600000
    refresh: 2592000000